import type { KnipConfig } from 'knip'
const config: KnipConfig = {
  entry: ['src/main.tsx', 'src/app/router.tsx', 'src/tests/**/*.{test,spec}.{ts,tsx}'],
  project: ['src/**/*.{ts,tsx}'],
  ignore: ['e2e/**'],
  ignoreDependencies: [
    '@types/*',
    '@radix-ui/react-tabs',
    '@radix-ui/react-dialog',
    '@radix-ui/react-visually-hidden',
    '@secretlint/secretlint-rule-preset-recommend',
    '@testing-library/user-event',
  ],
  ignoreExportsUsedInFile: true,
  // Disable duplicate-export rule — searchHistoryStore keeps legacy aliases intentionally
  rules: {
    duplicates: 'off',
  },
  ignoreFiles: [
    'src/components/ui/index.ts',
    'src/components/ui/skeleton/index.ts',
    'src/components/ui/skeleton/SkeletonBlock.tsx',
    'src/components/ui/skeleton/SkeletonCard.tsx',
    'src/components/ui/skeleton/SkeletonGrid.tsx',
    'src/components/ui/Toast.tsx',
    'src/features/favorites/hooks/index.ts',
    'src/features/favorites/index.ts',
    'src/features/filters/components/index.ts',
    'src/features/filters/hooks/index.ts',
    'src/features/filters/index.ts',
    'src/features/lists/components/index.ts',
    'src/features/lists/components/ListCard.tsx',
    'src/features/lists/index.ts',
    'src/features/movies/api/index.ts',
    'src/features/movies/components/index.ts',
    'src/features/movies/components/movie-modal/index.ts',
    'src/features/movies/components/movie-modal/MovieModalBackdrop.tsx',
    'src/features/movies/components/movie-modal/MovieModalDetails.tsx',
    'src/features/movies/components/movie-modal/MovieModalPoster.tsx',
    'src/features/movies/components/movie-modal/TrailerLightbox.tsx',
    'src/features/movies/components/movie-modal/useMovieModalState.ts',
    'src/features/movies/components/MovieModal.tsx',
    'src/features/movies/components/person/index.ts',
    'src/features/movies/components/SortableMovieCard.tsx',
    'src/features/movies/components/useSortableGrid.ts',
    'src/features/movies/hooks/index.ts',
    'src/features/movies/hooks/useMetaTags.ts',
    'src/features/movies/index.ts',
    'src/features/movies/types/index.ts',
    'src/features/search/index.ts',
    'src/features/shared/api/tmdbHelpers.ts',
    'src/features/tv/api/index.ts',
    'src/features/tv/components/index.ts',
    'src/features/tv/hooks/index.ts',
    'src/features/tv/index.ts',
    'src/features/tv/types/index.ts',
    'src/features/watched/index.ts',
    'src/hooks/useBrowseMedia.ts',
    'src/hooks/useListsPage.ts',
    'src/lib/i18n.ts',
    'src/lib/validation.ts',
  ],
}
export default config
