export { MiniPosterCard } from './MiniPosterCard'
export type { MiniPosterCardProps } from './MiniPosterCard'
export { PersonHeader } from './PersonHeader'
export type { PersonHeaderProps } from './PersonHeader'
export { PersonBio } from './PersonBio'
export type { PersonBioProps } from './PersonBio'
export { FilmographyGrid } from './FilmographyGrid'
export type { FilmographyGridProps } from './FilmographyGrid'
export { PersonFilmography } from './PersonFilmography'
export type { PersonFilmographyProps } from './PersonFilmography'
